// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3kbVZX6g3P3jt5onFa2Q9lutMMravKk',
    appId: '1:334621754331:web:7979931ce713f32065ddfe',
    messagingSenderId: '334621754331',
    projectId: 'casebehold',
    authDomain: 'casebehold.firebaseapp.com',
    storageBucket: 'casebehold.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJrx2YBAd9EiS4terCTc3t8pwqv2hJ9U',
    appId: '1:334621754331:android:2d1abe38d5ca056965ddfe',
    messagingSenderId: '334621754331',
    projectId: 'casebehold',
    storageBucket: 'casebehold.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvSzEVkM3EccoT5CpV6B8WxRLtOt674CA',
    appId: '1:334621754331:ios:89b0e23b4471be0465ddfe',
    messagingSenderId: '334621754331',
    projectId: 'casebehold',
    storageBucket: 'casebehold.firebasestorage.app',
    iosBundleId: 'com.example.casebehold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvSzEVkM3EccoT5CpV6B8WxRLtOt674CA',
    appId: '1:334621754331:ios:89b0e23b4471be0465ddfe',
    messagingSenderId: '334621754331',
    projectId: 'casebehold',
    storageBucket: 'casebehold.firebasestorage.app',
    iosBundleId: 'com.example.casebehold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq3kbVZX6g3P3jt5onFa2Q9lutMMravKk',
    appId: '1:334621754331:web:e360c2bd7594996b65ddfe',
    messagingSenderId: '334621754331',
    projectId: 'casebehold',
    authDomain: 'casebehold.firebaseapp.com',
    storageBucket: 'casebehold.firebasestorage.app',
  );
}